
deployment:
  tasks:
    # NOTE: public_html on cPanel must not be removed or renamed.
    # This folder has owner USER:nobody, and the USER user does not have
    # access to change owner. So this folder must stay as-is to keep the nobody
    # group, which is critical to the site working. A new folder won't work.
    - export DEPLOYPATH=/home/jamiatre/public_html/temp_deploy_path/
    - export REPOPATH=/home/jamiatre/public_html/test-ci-cd/ji-reporting-frontend
    # Remove previous old files, if any.
    - rm -Rf ${DEPLOYPATH}_old
    # Copy old site files to another directory.
    - cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    - zip -R new.zip ${DEPLOYPATH}
