export * from "./Colleges";
export * from "./IfradiKuwat";
export * from "./Jamiaat";
export * from "./Library";
export * from "./MarkaziActivities";
export * from "./OtherActivities";
export * from "./PaighamDigest";
export * from "./RozOShabDiary";
export * from "./Tanzeem";
export * from "./ToseeDawat";
export * from "./ZailiActivities"