import { Compile } from "../pages/Compilaton/Compile";

export const getLanguagePreference = () => {
  return localStorage.getItem("@lang") || 'english';
};

export const translate = (key) => {
  const lang = getLanguagePreference();
  return translations[lang][key];
};

const translations = {
  english: {
    Dashboard: "Dashboard",
    IJTReporting:"IJT Reporting",
    farewell: "Goodbye",
    profile: "Profile",
    ChangePassword:"Change Password",
    logout:"Logout",
    userRequest: "User Request(s)",
    Norequestsfound:"No Requests Found!",
    notifications: "Notification(s)",
    Nonotificationsfound:"No notifications found!",
    TotalNazims:"Total Nazims",
    TotalProvinces:"Total Provinces",
    TotalDivisions:"Total Divisions",
    TotalDistricts:"Total Districts",
    TotalTehsils:"Total Tehsils",
    TotalMaqams:"Total Maqams",
    TotalIlaqas:"Total Ilaqas",
    TotalUnits:"Total Units",
    CreateNewReport:"Create New Report",
    SeeReportsStatus:"See Reports Status",
    CloseReportsStatus:"Close Reports Status",
    Filter:"Filter",
    ClearFilter:"Clear Filter",
    PersonalFilled:"Personal Filled",
    PersonalUnfilled:"Personal Unfilled",
    Filled:"Filled",
    Unfilled:"Unfilled",
    Reportsof:"Reports of",
    Area:"Area",
    Nazim:"Nazim",
    View:"View",
    UserNotRegisteredYet:"User Not Registered Yet",
    UserNotRegistered:"User Not Registered",
    Noonehasfilledreportyet:"No one has filled report yet",
    Detailsofthearea:"Details of the area",
    Name:"Name",
    Halqa:"Halqa",
    Tehsil:"Tehsil",
    District:"District",
    Ilaqa:"Ilaqa",
    IlaqaZone:"Ilaqa/Zone",
    Division:"Division",
    Maqam:"Maqam",
    Province:"Province", 
    Country:"Country",
    Markaz:"Markaz",
    Close:"Close",
    Pakistan:"Pakistan",
    Clear:"Clear",
    Personal:"Personal",
    All:"All",
    AllhavefilledtheirpersonalReports:"All have filled their personal Reports",
    Noonehasfilledpersonalreportyet:"No one has filled personal report yet",
    Allhavefilledreports:"All have filled reports",
    Reports:'Reports',
    Report:'Report',
    NewReport:"NewReport",
    Compile:"Compile",
    arkanumeedwaranReport:"Arkan/Umeedwaran Reports",
    January: 'January',
    February: 'February',
    March: 'March',
    April: 'April',
    May: 'May',
    June: 'June',
    July: 'July',
    August: 'August',
    September: 'September',
    October: 'October',
    November: 'November',
    December: 'December',
    Search:"Search",
    filter:"filter",
    Clear:"Clear",
    maqamHalqa:"Maqam Halqa",
    divisionHalqa:"Division Halqa",
    ilaqaHalqa:"Ilaqa Halqa",
    LastModified:"LastModified",
    Previous:"Previous",
    Next:"Next",
    Page:"Page",
    of:"of",
    ReportsCompilation:"Reports Compilation",
    SelectAreaType:"Select Area Type",
    SelectArea:"Select Area",
    SelectHalqa:"Select Halqa",
    Byyear:"By year",
    Bymonth:"By month",
    StartDate:"Start Date",
    EndDate:"End Date",
    NoReportsFound:"No Reports Found",
    ReportType:"Report Type",
    halqa:"حلقہ",
    tehsil:"تحصیل",
    district:"ضلع",
    ilaqa:"علاقہ",
    division:"ڈویژن",
    maqam:"مقام",
    province:"صوبہ", 
    country:"مُلک",
    pakistan:"پاکستان",
    personal:"ذاتی",
    Property:"Property",
    RadialChart:"Radial Chart",
    SpiderChart:"Spider Chart",
    CompareAll:"Compare All",
    spiderChart:"Spider Chart",
    compareAll:"Compare All",
    ToseeDawat:"ToseeDawat",
    Mutalajaat:"Mutalajaat",
    Prayers:"Prayers",
    DurationType:"Duration Type",
    Month:"Month",
    Year:"Year",
    Dates:"Dates",
    Generate:"Generate",
    Add:"Add",
    EditDisable:"Edit/Disable",
    AreaDetails:"Area Details"
  },
  urdu: {
    Dashboard: "ڈیش بورڈ",
    IJTReporting: "آئ جے ٹی رپورٹنگ",
    profile: "پروفائل",
    ChangePassword:"تبدیل پاسورڈ",
    logout:"لاگ آؤٹ",
    userRequest: "صارفین کی درخواستیں",
    Norequestsfound:"کوئ درخواست نہیں ملی!",
    notifications: "اطلاعات",
    Nonotificationsfound:"کوئ اطلاع نہیں ملی!",
    TotalNazims:"کُل ناظم",
    TotalProvinces:"کُل صوبے",
    TotalDivisions:"کُل ڈویژن",
    TotalDistricts:"کُل ضلع",
    TotalTehsils:"کُل تحصیل",
    TotalMaqams:"کُل مقام",
    TotalIlaqas:"کُل علاقے",
    TotalUnits:"کُل یونٹ",
    CreateNewReport:"نئ رپورٹ بنائیں",
    SeeReportsStatus:"رپورٹس کا سٹیٹس دیکھیں",
    CloseReportsStatus:"رپورٹس کا سٹیٹس بند کریں",
    Filter:"فلٹر",
    ClearFilter:"صاف فلٹر",
    PersonalFilled:"ذاتی فِل کی ہوئ",
    PersonalUnfilled:"ذاتی فِل نا کی ہوئ",
    Filled:"فِل",
    Unfilled:"غیر فِل",
    Reportsof:"کی رپورٹیں",
    Area:"علاقہ",
    Nazim:"ناظم",
    View:"تفصیل",
    UserNotRegisteredYet:"صارف ابھی رجسٹر نہیں",
    UserNotRegistered:"صارف رجسٹر نہیں",
    Noonehasfilledreportyet:"ابھی کسی نے رپورٹ فِل نہیں کی",
    Detailsofthearea:"علاقہ کی تفصیل",
    Name:"نام",
    Halqa:"حلقہ",
    Tehsil:"تحصیل",
    District:"ضلع",
    Ilaqa:"علاقہ",
    IlaqaZone:"علاقہ/زون",
    Division:"ڈویژن",
    Maqam:"مقام",
    Province:"صوبہ", 
    Country:"مُلک",
    Close:"بند کریں",
    Pakistan:"پاکستان",
    Clear:"صالف کریں",
    Personal:"ذاتی",
    All:"تمام",
    Markaz:"مرکز",
    AllhavefilledtheirpersonalReports:"سب نے اپنی ذاتی رپورٹیں بھر دی ہیں۔",
    Noonehasfilledpersonalreportyet:"ابھی تک کسی نے ذاتی رپورٹ نہیں بھری ہے۔",
    Allhavefilledreports:"سب نے رپورٹیں بھر دی ہیں۔",
    Reports:'رپورٹیں',
    Report:'رپورٹ',
    NewReport:"نئ رپورٹ",
    Compile:"مرتب کریں",
    arkanumeedwaranReport:"ارکان/امیدواران رپورٹ",
    January: 'جنوری',
    February: 'فروری',
    March: 'مارچ',
    April: 'اپریل',
    May: 'مئی',
    June: 'جون',
    July: 'جولائی',
    August: 'اگست',
    September: 'ستمبر',
    October: 'اکتوبر',
    November: 'نومبر',
    December: 'دسمبر',
    Search:"تلاش کریں",
    filter:"فلٹر",
    Clear:"صاف کریں",
    maqamHalqa:"مقام حلقہ",
    divisionHalqa:"ڈویژن حلقہ",
    ilaqaHalqa:"علاقہ حلقہ",
    LastModified:"آخری ترمیم",
    Previous:"پچھلا",
    Next:"اگلا",
    Page:"صفحہ",
    of:"-کُل",
    ReportsCompilation:"رپورٹس کی تالیف",
    SelectAreaType:"ایریا کی قسم کا انتخاب کریں",
    SelectArea:"انتخاب ایریا",
    SelectHalqa:"انتخاب حلقہ",
    Byyear:"سال سے",
    Bymonth:"مہینہ سے",
    StartDate:"آغاز تاریخ",
    EndDate:"اختمام تاریخ",
    NoReportsFound:"کوئی رپورٹ نہیں ملی",
    ReportType:"رپورٹ کی قسم",
    halqa:"حلقہ",
    tehsil:"تحصیل",
    district:"ضلع",
    ilaqa:"علاقہ",
    division:"ڈویژن",
    maqam:"مقام",
    province:"صوبہ", 
    country:"مُلک",
    pakistan:"پاکستان",
    personal:"ذاتی",
    Property:"خصوصیت",
    RadialChart:"ریڈیل چارٹ",
    SpiderChart:"سپائڈر چارٹ",
    CompareAll:"موازنہ تمام",
    spiderChart:"سپائڈر چارٹ",
    compareAll:"موازنہ تمام",
    ToseeDawat:"توسیع دعوت",
    Mutalajaat:"مطالعہ جات",
    Prayers:"نمازیں",
    DurationType:"مدت کی قسم",
    Month:"ماہ",
    Year:"سال",
    Dates:"تاریخ",
    Generate:"بنائیں",
    Add:"اضافہ",
    EditDisable:"ترمیم/غیر فعال",
    AreaDetails:"ایریا تفصیل"


  },
};
